import Head from 'next/head'
import Registration from './registration'

export default function Home() {
	
	return (
		<>
			<Head>
				<title>Travel</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="#"/>
				<link rel="preconnect" href="https://fonts.googleapis.com"/>
				<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet"/>
			</Head>
			<Registration/>
		</>
	)
}
